categories:
  - title: Featured applications
    description: |
      Skupper works with your existing application code, no changes
      required.  These examples highlight Skupper's ability to deploy
      conventional applications across multiple sites.
    examples:
      - name: skupper-example-hello-world
        title: Hello World
      - name: skupper-example-patient-portal
        title: Patient Portal
      - name: skupper-example-trade-zoo
        title: Trade Zoo
      - name: skupper-example-bookinfo
        title: Bookinfo
        video_url: https://www.youtube.com/watch?v=H80GLl-KdTc
      - name: skupper-example-grpc
        title: Online Boutique
      - name: skupper-example-http-load-balancing
        title: HTTP load balancing
        video_url: https://www.youtube.com/watch?v=4GmXT3nj8lc
  - title: Connectivity scenarios
    description: |
      Skupper helps you overcome tough networking obstacles.  See how
      you can securely connect services in sites behind firewalls or
      NAT without changing your existing networking.
    examples:
      - name: skupper-example-public-to-private
        title: Public to private
        description: |
          <div style="padding-bottom: 0.8em;">
            <span class="material-symbols-outlined">cloud</span>
            <span class="material-symbols-outlined">horizontal_rule</span>
            <span class="material-symbols-outlined">business</span>
          </div>
          Connect from the cloud to services running on-prem
      - name: skupper-example-private-to-private
        title: Private to private
        description: |
          <div style="padding-bottom: 0.8em;">
            <span class="material-symbols-outlined">business</span>
            <span class="material-symbols-outlined">horizontal_rule</span>
            <span class="material-symbols-outlined">cloud</span>
            <span class="material-symbols-outlined">horizontal_rule</span>
            <span class="material-symbols-outlined">business</span>
          </div>
          Connect services in isolated on-prem sites
      - name: skupper-example-dmz
        title: DMZ
        description: |
          <div style="padding-bottom: 0.8em;">
            <span class="material-symbols-outlined">cloud</span>
            <span class="material-symbols-outlined">horizontal_rule</span>
            <span class="material-symbols-outlined">shield</span>
            <span class="material-symbols-outlined">horizontal_rule</span>
            <span class="material-symbols-outlined">business</span>
          </div>
          Connect services separated by firewalls and a DMZ
  - title: Platforms
    description: |
      Skupper works with services running as pods on Kubernetes, as
      containers, or as ordinary processes on bare metal hosts or VMs.
    examples:
      - name: skupper-example-hello-world
        title: Kubernetes
        description: |
          Connect services running as pods in Kubernetes
      - name: skupper-example-containers
        title: Docker or Podman
      - name: skupper-example-gateway
        title: Bare metal or VM
  - title: Database examples
    description: |
      With Skupper you can locate your data wherever you need it to
      be, while accessing it from wherever your services are running.
    examples:
      - name: skupper-example-mongodb-replica-set
        title: MongoDB
      - name: skupper-example-mysql
        title: MySQL
      - name: skupper-example-postgresql
        title: PostgreSQL
        video_url: https://www.youtube.com/watch?v=Oa0aVpb0v7U
  - title: Messaging examples
    description: |
      Skupper helps you access message queues and connect event-driven
      applications spread across isolated network locations.
    examples:
      - name: skupper-example-activemq
        title: ActiveMQ
      - name: skupper-example-kafka
        title: Kafka
        video_url: https://www.youtube.com/watch?v=W7aUOgCTyOg
      - name: skupper-example-rabbitmq
        title: RabbitMQ
  - title: Protocol examples
    description: |
      Skupper supports any TCP-based protocol.  These examples show
      how you can access services based on widely used internet
      protocols.
    examples:
      - name: skupper-example-tcp
        title: TCP
        video_url: https://www.youtube.com/watch?v=ZQo9cB0-1go
      - name: skupper-example-http
        title: HTTP
      - name: skupper-example-ftp
        title: FTP
  - title: Other examples
    examples:
      - name: skupper-example-camel-integration
        title: Camel
      - name: skupper-example-iperf
        title: iPerf
      - name: skupper-example-prometheus
        title: Prometheus
      - name: skupper-example-declarative
        title: YAML Hello World
